name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download zig
        run: wget https://ziglang.org/builds/zig-0.14.0-dev.2639+15fe99957.tar.xz

      - name: Extract
        run: tar -xf zig-0.14.0-dev.2639+15fe99957.tar.xz

      - name: Alias
        run: alias zig=$PWD/zig-0.14.0-dev.2639+15fe99957/lib/zig

      - name: Version
        run: zig version

      - name: Test
        run: zig build test