name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download zig
        run: wget https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.1622+2ac543388.tar.xz

      - name: Extract
        run: tar -xf zig-linux-x86_64-0.14.0-dev.1622+2ac543388.tar.xz

      - name: Alias
        run: echo "alias zig=$PWD/zig-linux-x86_64-0.14.0-dev.1622+2ac543388/zig" >> $GITHUB_ENV

      - name: Version
        run: $PWD/zig-linux-x86_64-0.14.0-dev.1622+2ac543388/zig version

      - name: Test
        run: $PWD/zig-linux-x86_64-0.14.0-dev.1622+2ac543388/zig build test